<a href="https://colab.research.google.com/github/sanattaori/PadhAI/blob/master/Basic_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [0]:
import numpy as np

In [2]:
X = np.array([1,2,3])
print(X)

[1 2 3]


In [3]:
type(X)

numpy.ndarray

In [7]:
# convert any list to array
l = [10,20,30]
X = np.asarray(l)
type(X)

numpy.ndarray

In [6]:
X

array([10, 20, 30])

In [8]:
X = np.asarray(l,float)
X

array([10., 20., 30.])

In [9]:
X.shape
# 1d array

(3,)

In [0]:
X = np.array(([1,2,3],[4,5,6]))

In [11]:
X.shape

(2, 3)

In [17]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# accessing items from array
X[1:2]

array([[4, 5, 6]])

In [16]:
X[0,0:2]

array([1, 2])

In [0]:
X = np.eye(4,4)

In [22]:
X

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
X = np.random.random((4,5))

In [24]:
X

array([[0.08044772, 0.94217349, 0.41051888, 0.15004236, 0.1024594 ],
       [0.75282445, 0.77692254, 0.69838646, 0.08347496, 0.52721366],
       [0.35727099, 0.89201978, 0.3319606 , 0.41937626, 0.13471982],
       [0.10059323, 0.67331061, 0.79252201, 0.71957278, 0.59548033]])

In [0]:
Z = X.T

In [27]:
Z

array([[0.08044772, 0.75282445, 0.35727099, 0.10059323],
       [0.94217349, 0.77692254, 0.89201978, 0.67331061],
       [0.41051888, 0.69838646, 0.3319606 , 0.79252201],
       [0.15004236, 0.08347496, 0.41937626, 0.71957278],
       [0.1024594 , 0.52721366, 0.13471982, 0.59548033]])

In [0]:
Y = X.reshape(20,1)

In [33]:
Y

array([[0.08044772],
       [0.94217349],
       [0.41051888],
       [0.15004236],
       [0.1024594 ],
       [0.75282445],
       [0.77692254],
       [0.69838646],
       [0.08347496],
       [0.52721366],
       [0.35727099],
       [0.89201978],
       [0.3319606 ],
       [0.41937626],
       [0.13471982],
       [0.10059323],
       [0.67331061],
       [0.79252201],
       [0.71957278],
       [0.59548033]])

In [0]:
A = np.arange(5)

In [35]:
A

array([0, 1, 2, 3, 4])

In [36]:
print(A, A+1)

[0 1 2 3 4] [1 2 3 4 5]


In [0]:
#integers bw 0-10
A = np.floor(np.random.random((2,3))*10)

In [38]:
A

array([[4., 5., 6.],
       [0., 6., 5.]])

In [39]:
u1 = [1,2,3]
v = [-1,0,1]

p1 = np.inner(u1,v)
print(p1)

2


In [0]:
p2 = np.outer(u1,v)

In [41]:
p2

array([[-1,  0,  1],
       [-2,  0,  2],
       [-3,  0,  3]])

In [0]:
A = np.ones((2,3))
B = np.ones((3,2))

In [44]:
np.dot(A,B)

array([[3., 3.],
       [3., 3.]])

In [45]:
A.sum()

6.0

In [46]:
# column sums
A.sum(axis=0)

array([2., 2., 2.])

In [47]:
# row sums
A.sum(axis=1)

array([3., 3.])